---
title: "Capstone Project Proposal"
author: "Anthony Stachowitz"
date: "July 11, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Project Idea:  Boston Housing Dataset (Small dataset (506 cases) provided by the U.S. Census Service concerning housing in Boston Mass..


#### Central Question

What Assessments can be made about Boston real estate from this sample set of data from the U.S. Census Service?

To help answer this central question, I would investigate the following more specific questions:

1. What is the relation of the per capital crime rate by town to the pupil-teacher ratio by town?
2. What is the relation of the per capital crime rate by town to the proportion of blacks by town?
3. What is the relation of the per capital crime rate by town to the median value of owner-occupied homes?
4. What is the relation of the per capital crime rate by town to the status of the population?
5. Does pupil-teacher ratio, blacks by town, median value of owner occupied homes, or status of the population have the most relevant correlation to the capital crime rate by town?


#### Client and Motivation
I am looking at this issue from the perspective of the city counsel investigating possible reasons for the per capital crime rate by town. The city council is always looking at ways to reduce crime and wants to know what collected variables corollate most to the rate of crime in different parts of the city. The collected information will be used to propose future solutions to help to lower the capital crime rate. 


#### Data

The data can be found in the GitHub repository at https://github.com/stackdata/boston/blob/master/bosto_dataset_raw.xls.  It's in an easily downloadable xls format.


#### Outline of Approach

1) Clean up data and fill any missing data with appropriate information and rename columns appropriately.
2) Start to explore data through statistical summaries and plots. 
	  look at relationships between pupil-teacher ratio and crime data.
	  look at the relations ships between blacks and crime data.
	  look at the relationship between median value of owner-occupied homes and crime data.
	  look at the relationship between status of the population and crime data.
3) Identify relationship connections and use statistical tests to quantify the strength of the relationship.


#### Deliverables
Deliver a report with my findings and a conclusion.


